on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    name: Greeting
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hello
        id: hello
        uses: ./
      - run: |
          echo ${{ steps.hello.outputs.test }}
          echo ${{ steps.hello.outputs.hoge }}
          echo ${{ steps.hello.outputs.result }}
